name: Build, Push Docker Image & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build Java Project
        run: mvn clean package --file pom.xml

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: "anthony8800"
          password: "ANTHONY_PASSWORD"  # 🔔 RECOMMENDED: Use GitHub Secret, don't hardcode password

      - name: Build Docker Image
        run: docker build -t anthony8800/my-java-app .

      - name: Push Docker Image to DockerHub
        run: docker push anthony8800/my-java-app

      # 🚀 Deploy to EC2 with Docker installation
      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 174.129.129.249
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            echo "Deploying Docker container..."
            sudo docker pull anthony8800/my-java-app
            sudo docker pull anthony8800/my-python-app
            sudo docker stop my-java-container || true
            sudo docker rm my-java-container || true
            sudo docker run -d -p 5009:8080 --name my-java-container anthony8800/my-java-app
            sudo docker run -d -p 5010:5000 anthony8800/my-python-app
